# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'ARtest' do
  # Comment the next line if you don't want to use dynamic frameworks
	pod 'SwiftyJSON'
	pod 'Alamofire', '4.8.0'
	pod 'Cartography'

  use_frameworks!

  # Pods for ARtest

  target 'ARtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARtestUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      end
    end
  end

end
